version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ai/console/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/calendar/board/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/crud/ui/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/kanban/board/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/sidebar/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ui/data-display/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ui/filters/ts"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/ui/forms/ts"
    schedule:
      interval: "weekly"
